version: '3'
services:
  front-end:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    container_name: front-end-next
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - react-mongo-network
    ports:
      - "3001:3000"
    command: >
      sh -c "npm install && npm run dev"

#Docker Networks
networks:
  react-mongo-network:
    driver: bridge
